//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REBUSS.Pure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REBUSS.Pure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.json.
        /// </summary>
        internal static string AppSettingsFileName {
            get {
                return ResourceManager.GetString("AppSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.Local.json.
        /// </summary>
        internal static string AppSettingsLocalFileName {
            get {
                return ResourceManager.GetString("AppSettingsLocalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to init.
        /// </summary>
        internal static string CliCommandInit {
            get {
                return ResourceManager.GetString("CliCommandInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string ConfigKeyProvider {
            get {
                return ResourceManager.GetString("ConfigKeyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch diff requires at least one commit in the repository. Create an initial commit first, then retry..
        /// </summary>
        internal static string ErrorBranchDiffRequiresCommits {
            get {
                return ResourceManager.GetString("ErrorBranchDiffRequiresCommits", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to start process.
        /// </summary>
        internal static string ErrorFailedToStartProcess {
            get {
                return ResourceManager.GetString("ErrorFailedToStartProcess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] FATAL: {1}: {2}.
        /// </summary>
        internal static string ErrorFatalMessage {
            get {
                return ResourceManager.GetString("ErrorFatalMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File '{0}' not found among local changes (scope: {1}).
        /// </summary>
        internal static string ErrorFileNotFoundAmongLocalChanges {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundAmongLocalChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File not found in local changes: {0}.
        /// </summary>
        internal static string ErrorFileNotFoundInLocalChanges {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundInLocalChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File not found in Pull Request: {0}.
        /// </summary>
        internal static string ErrorFileNotFoundInPullRequest {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundInPullRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Git command failed: {0}.
        /// </summary>
        internal static string ErrorGitCommandFailed {
            get {
                return ResourceManager.GetString("ErrorGitCommandFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to git exited with code {0}: {1}.
        /// </summary>
        internal static string ErrorGitExitedWithCode {
            get {
                return ResourceManager.GetString("ErrorGitExitedWithCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] INNER: {1}: {2}.
        /// </summary>
        internal static string ErrorInnerMessage {
            get {
                return ResourceManager.GetString("ErrorInnerMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter: pageNumber.
        /// </summary>
        internal static string ErrorMissingRequiredPageNumber {
            get {
                return ResourceManager.GetString("ErrorMissingRequiredPageNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter: prNumber.
        /// </summary>
        internal static string ErrorMissingRequiredPrNumber {
            get {
                return ResourceManager.GetString("ErrorMissingRequiredPrNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No git repository root could be resolved...
        /// </summary>
        internal static string ErrorNoGitRepositoryRoot {
            get {
                return ResourceManager.GetString("ErrorNoGitRepositoryRoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: Not inside a Git repository...
        /// </summary>
        internal static string ErrorNotInsideGitRepository {
            get {
                return ResourceManager.GetString("ErrorNotInsideGitRepository", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to pageNumber {0} exceeds total pages {1}.
        /// </summary>
        internal static string ErrorPageNumberExceedsTotalPages {
            get {
                return ResourceManager.GetString("ErrorPageNumberExceedsTotalPages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to pageNumber must be >= 1.
        /// </summary>
        internal static string ErrorPageNumberMustBePositive {
            get {
                return ResourceManager.GetString("ErrorPageNumberMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page number {0} is out of range. Valid range: 1 to {1}.
        /// </summary>
        internal static string ErrorPageNumberOutOfRange {
            get {
                return ResourceManager.GetString("ErrorPageNumberOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to prNumber must be greater than 0.
        /// </summary>
        internal static string ErrorPrNumberMustBePositive {
            get {
                return ResourceManager.GetString("ErrorPrNumberMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pull Request not found: {0}.
        /// </summary>
        internal static string ErrorPullRequestNotFound {
            get {
                return ResourceManager.GetString("ErrorPullRequestNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repository not found: {0}.
        /// </summary>
        internal static string ErrorRepositoryNotFound {
            get {
                return ResourceManager.GetString("ErrorRepositoryNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving file diff: {0}.
        /// </summary>
        internal static string ErrorRetrievingFileDiff {
            get {
                return ResourceManager.GetString("ErrorRetrievingFileDiff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving local content: {0}.
        /// </summary>
        internal static string ErrorRetrievingLocalContent {
            get {
                return ResourceManager.GetString("ErrorRetrievingLocalContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving local file diff: {0}.
        /// </summary>
        internal static string ErrorRetrievingLocalFileDiff {
            get {
                return ResourceManager.GetString("ErrorRetrievingLocalFileDiff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving local files: {0}.
        /// </summary>
        internal static string ErrorRetrievingLocalFiles {
            get {
                return ResourceManager.GetString("ErrorRetrievingLocalFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving PR content: {0}.
        /// </summary>
        internal static string ErrorRetrievingPrContent {
            get {
                return ResourceManager.GetString("ErrorRetrievingPrContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving PR diff: {0}.
        /// </summary>
        internal static string ErrorRetrievingPrDiff {
            get {
                return ResourceManager.GetString("ErrorRetrievingPrDiff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving PR files: {0}.
        /// </summary>
        internal static string ErrorRetrievingPrFiles {
            get {
                return ResourceManager.GetString("ErrorRetrievingPrFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving PR metadata: {0}.
        /// </summary>
        internal static string ErrorRetrievingPrMetadata {
            get {
                return ResourceManager.GetString("ErrorRetrievingPrMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}.
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to git.
        /// </summary>
        internal static string GitExecutable {
            get {
                return ResourceManager.GetString("GitExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote get-url origin.
        /// </summary>
        internal static string GitRemoteGetUrlArgs {
            get {
                return ResourceManager.GetString("GitRemoteGetUrlArgs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rev-parse --abbrev-ref HEAD.
        /// </summary>
        internal static string GitRevParseAbbrevRefHead {
            get {
                return ResourceManager.GetString("GitRevParseAbbrevRefHead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to rev-parse --verify HEAD.
        /// </summary>
        internal static string GitRevParseVerifyHead {
            get {
                return ResourceManager.GetString("GitRevParseVerifyHead", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_content] Completed: page {Page}/{TotalPages}, ...
        /// </summary>
        internal static string LogGetLocalContentCompleted {
            get {
                return ResourceManager.GetString("LogGetLocalContentCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_content] Entry: page {PageNumber}, scope={Scope}.
        /// </summary>
        internal static string LogGetLocalContentEntry {
            get {
                return ResourceManager.GetString("LogGetLocalContentEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_content] Error (pageNumber={PageNumber}, scope={Scope}).
        /// </summary>
        internal static string LogGetLocalContentError {
            get {
                return ResourceManager.GetString("LogGetLocalContentError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_files] Completed (F003): scope={Scope}, ...
        /// </summary>
        internal static string LogGetLocalFilesCompletedF003 {
            get {
                return ResourceManager.GetString("LogGetLocalFilesCompletedF003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_files] Completed (F004): scope={Scope}, ...
        /// </summary>
        internal static string LogGetLocalFilesCompletedF004 {
            get {
                return ResourceManager.GetString("LogGetLocalFilesCompletedF004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_files] Entry: scope={Scope}.
        /// </summary>
        internal static string LogGetLocalFilesEntry {
            get {
                return ResourceManager.GetString("LogGetLocalFilesEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_files] Error.
        /// </summary>
        internal static string LogGetLocalFilesError {
            get {
                return ResourceManager.GetString("LogGetLocalFilesError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_files] Git command failed.
        /// </summary>
        internal static string LogGetLocalFilesGitCommandFailed {
            get {
                return ResourceManager.GetString("LogGetLocalFilesGitCommandFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_local_files] Repository not found.
        /// </summary>
        internal static string LogGetLocalFilesRepositoryNotFound {
            get {
                return ResourceManager.GetString("LogGetLocalFilesRepositoryNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_content] Completed: PR #{PrNumber}, page {Page}/{TotalPages}, ...
        /// </summary>
        internal static string LogGetPrContentCompleted {
            get {
                return ResourceManager.GetString("LogGetPrContentCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_content] Entry: PR #{PrNumber}, page {PageNumber}.
        /// </summary>
        internal static string LogGetPrContentEntry {
            get {
                return ResourceManager.GetString("LogGetPrContentEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_content] Error (prNumber={PrNumber}, pageNumber={PageNumber}).
        /// </summary>
        internal static string LogGetPrContentError {
            get {
                return ResourceManager.GetString("LogGetPrContentError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_content] PR not found (prNumber={PrNumber}).
        /// </summary>
        internal static string LogGetPrContentPrNotFound {
            get {
                return ResourceManager.GetString("LogGetPrContentPrNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_files] Completed (F003): PR #{PrNumber}, ...
        /// </summary>
        internal static string LogGetPrFilesCompletedF003 {
            get {
                return ResourceManager.GetString("LogGetPrFilesCompletedF003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_files] Completed (F004): PR #{PrNumber}, ...
        /// </summary>
        internal static string LogGetPrFilesCompletedF004 {
            get {
                return ResourceManager.GetString("LogGetPrFilesCompletedF004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_files] Entry: PR #{PrNumber}.
        /// </summary>
        internal static string LogGetPrFilesEntry {
            get {
                return ResourceManager.GetString("LogGetPrFilesEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_files] Error.
        /// </summary>
        internal static string LogGetPrFilesError {
            get {
                return ResourceManager.GetString("LogGetPrFilesError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_files] Could not fetch metadata for fingerprint.
        /// </summary>
        internal static string LogGetPrFilesMetadataFingerprintFailed {
            get {
                return ResourceManager.GetString("LogGetPrFilesMetadataFingerprintFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_files] Pull request not found.
        /// </summary>
        internal static string LogGetPrFilesPrNotFound {
            get {
                return ResourceManager.GetString("LogGetPrFilesPrNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_metadata] Completed: PR #{PrNumber}, {ResponseLength} chars, {ElapsedMs}ms.
        /// </summary>
        internal static string LogGetPrMetadataCompleted {
            get {
                return ResourceManager.GetString("LogGetPrMetadataCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_metadata] Entry: PR #{PrNumber}.
        /// </summary>
        internal static string LogGetPrMetadataEntry {
            get {
                return ResourceManager.GetString("LogGetPrMetadataEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_metadata] Error (prNumber={PrNumber}).
        /// </summary>
        internal static string LogGetPrMetadataError {
            get {
                return ResourceManager.GetString("LogGetPrMetadataError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [get_pr_metadata] Pull request not found (prNumber={PrNumber}).
        /// </summary>
        internal static string LogGetPrMetadataNotFound {
            get {
                return ResourceManager.GetString("LogGetPrMetadataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine current branch.
        /// </summary>
        internal static string LogLocalGitClientCouldNotDetermineBranch {
            get {
                return ResourceManager.GetString("LogLocalGitClientCouldNotDetermineBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File '{Path}' not found at ref '{Ref}': {Error}.
        /// </summary>
        internal static string LogLocalGitClientFileNotFoundAtRef {
            get {
                return ResourceManager.GetString("LogLocalGitClientFileNotFoundAtRef", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repository at {Root} has no HEAD (no commits yet); using fallback commands.
        /// </summary>
        internal static string LogLocalGitClientNoHead {
            get {
                return ResourceManager.GetString("LogLocalGitClientNoHead", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running: git {Args} (in {Root}).
        /// </summary>
        internal static string LogLocalGitClientRunning {
            get {
                return ResourceManager.GetString("LogLocalGitClientRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fetching local file diff: path='{Path}', scope={Scope}, root={Root}.
        /// </summary>
        internal static string LogLocalReviewProviderFetchingFileDiff {
            get {
                return ResourceManager.GetString("LogLocalReviewProviderFetchingFileDiff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fetching local files: scope={Scope}, root={Root}.
        /// </summary>
        internal static string LogLocalReviewProviderFetchingFiles {
            get {
                return ResourceManager.GetString("LogLocalReviewProviderFetchingFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local file diff completed: path='{Path}', scope={Scope}, ...
        /// </summary>
        internal static string LogLocalReviewProviderFileDiffCompleted {
            get {
                return ResourceManager.GetString("LogLocalReviewProviderFileDiffCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File '{Path}' not found in local changes (scope={Scope}).
        /// </summary>
        internal static string LogLocalReviewProviderFileNotFound {
            get {
                return ResourceManager.GetString("LogLocalReviewProviderFileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local files completed: scope={Scope}, {FileCount} file(s), ...
        /// </summary>
        internal static string LogLocalReviewProviderFilesCompleted {
            get {
                return ResourceManager.GetString("LogLocalReviewProviderFilesCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CLI --repo value '{Path}' looks like an unexpanded variable...
        /// </summary>
        internal static string LogMcpWorkspaceRootProviderUnexpandedVariable {
            get {
                return ResourceManager.GetString("LogMcpWorkspaceRootProviderUnexpandedVariable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allocated {TotalItems} items across {TotalPages} pages, budget={Budget}.
        /// </summary>
        internal static string LogPageAllocatorAllocated {
            get {
                return ResourceManager.GetString("LogPageAllocatorAllocated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Budget {Budget} below minimum {Minimum}.
        /// </summary>
        internal static string LogPageAllocatorBudgetBelowMinimum {
            get {
                return ResourceManager.GetString("LogPageAllocatorBudgetBelowMinimum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty candidates, returning single empty page.
        /// </summary>
        internal static string LogPageAllocatorEmptyCandidates {
            get {
                return ResourceManager.GetString("LogPageAllocatorEmptyCandidates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleted legacy prompt file: {0}.
        /// </summary>
        internal static string MsgDeletedLegacyPromptFile {
            get {
                return ResourceManager.GetString("MsgDeletedLegacyPromptFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied {0} prompt file(s) to {1}.
        /// </summary>
        internal static string MsgCopiedPrompts {
            get {
                return ResourceManager.GetString("MsgCopiedPrompts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created MCP configuration ({0}): {1}.
        /// </summary>
        internal static string MsgCreatedMcpConfiguration {
            get {
                return ResourceManager.GetString("MsgCreatedMcpConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The MCP server will be launched with --repo pointing to your workspace.
        /// </summary>
        internal static string MsgMcpServerRepoHint {
            get {
                return ResourceManager.GetString("MsgMcpServerRepoHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart your IDE or reload the MCP client to pick up the new configuration.
        /// </summary>
        internal static string MsgRestartIdeHint {
            get {
                return ResourceManager.GetString("MsgRestartIdeHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updated MCP configuration ({0}): {1}.
        /// </summary>
        internal static string MsgUpdatedMcpConfiguration {
            get {
                return ResourceManager.GetString("MsgUpdatedMcpConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.
        /// </summary>
        internal static string ServerVersion {
            get {
                return ResourceManager.GetString("ServerVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning: Embedded prompt resource not found: {0}.
        /// </summary>
        internal static string WarnEmbeddedPromptResourceNotFound {
            get {
                return ResourceManager.GetString("WarnEmbeddedPromptResourceNotFound", resourceCulture);
            }
        }

        internal static string CopilotSetup_ExplainBenefit {
            get { return ResourceManager.GetString("CopilotSetup_ExplainBenefit", resourceCulture)!; }
        }

        internal static string CopilotSetup_PromptInstallGhAndContinue {
            get { return ResourceManager.GetString("CopilotSetup_PromptInstallGhAndContinue", resourceCulture)!; }
        }

        internal static string CopilotSetup_PromptInstallExtension {
            get { return ResourceManager.GetString("CopilotSetup_PromptInstallExtension", resourceCulture)!; }
        }

        internal static string CopilotSetup_AlreadyInstalled {
            get { return ResourceManager.GetString("CopilotSetup_AlreadyInstalled", resourceCulture)!; }
        }

        internal static string CopilotSetup_InstallSuccess {
            get { return ResourceManager.GetString("CopilotSetup_InstallSuccess", resourceCulture)!; }
        }

        internal static string CopilotSetup_InstallFailed {
            get { return ResourceManager.GetString("CopilotSetup_InstallFailed", resourceCulture)!; }
        }

        internal static string CopilotSetup_DeclineBannerTitle {
            get { return ResourceManager.GetString("CopilotSetup_DeclineBannerTitle", resourceCulture)!; }
        }

        internal static string CopilotSetup_DeclineBannerBody {
            get { return ResourceManager.GetString("CopilotSetup_DeclineBannerBody", resourceCulture)!; }
        }

        internal static string CopilotSetup_ManualInstallHint {
            get { return ResourceManager.GetString("CopilotSetup_ManualInstallHint", resourceCulture)!; }
        }

        internal static string LogCopilotClientStarting {
            get { return ResourceManager.GetString("LogCopilotClientStarting", resourceCulture)!; }
        }

        internal static string LogCopilotClientStarted {
            get { return ResourceManager.GetString("LogCopilotClientStarted", resourceCulture)!; }
        }

        internal static string LogCopilotClientStartFailed {
            get { return ResourceManager.GetString("LogCopilotClientStartFailed", resourceCulture)!; }
        }

        internal static string LogCopilotClientStopping {
            get { return ResourceManager.GetString("LogCopilotClientStopping", resourceCulture)!; }
        }

        internal static string LogCopilotAvailable {
            get { return ResourceManager.GetString("LogCopilotAvailable", resourceCulture)!; }
        }

        internal static string LogCopilotNotAvailable {
            get { return ResourceManager.GetString("LogCopilotNotAvailable", resourceCulture)!; }
        }

        internal static string LogCopilotReviewTriggered {
            get { return ResourceManager.GetString("LogCopilotReviewTriggered", resourceCulture)!; }
        }

        internal static string LogCopilotReviewPageStarted {
            get { return ResourceManager.GetString("LogCopilotReviewPageStarted", resourceCulture)!; }
        }

        internal static string LogCopilotReviewPageCompleted {
            get { return ResourceManager.GetString("LogCopilotReviewPageCompleted", resourceCulture)!; }
        }

        internal static string LogCopilotReviewPageFailed {
            get { return ResourceManager.GetString("LogCopilotReviewPageFailed", resourceCulture)!; }
        }

        internal static string LogCopilotReviewCompleted {
            get { return ResourceManager.GetString("LogCopilotReviewCompleted", resourceCulture)!; }
        }

        internal static string LogCopilotReviewFailed {
            get { return ResourceManager.GetString("LogCopilotReviewFailed", resourceCulture)!; }
        }

        internal static string CopilotReviewModeHeader {
            get { return ResourceManager.GetString("CopilotReviewModeHeader", resourceCulture)!; }
        }

        internal static string ErrorCopilotRequired {
            get { return ResourceManager.GetString("ErrorCopilotRequired", resourceCulture)!; }
        }

        internal static string LogCopilotReviewUnavailable {
            get { return ResourceManager.GetString("LogCopilotReviewUnavailable", resourceCulture)!; }
        }

        internal static string LogCopilotReviewAuthenticatedSuccess {
            get { return ResourceManager.GetString("LogCopilotReviewAuthenticatedSuccess", resourceCulture)!; }
        }

        internal static string LogCopilotFreeTierShapeWarning {
            get { return ResourceManager.GetString("LogCopilotFreeTierShapeWarning", resourceCulture)!; }
        }

        internal static string ErrorCopilotNotAuthenticatedRemediation {
            get { return ResourceManager.GetString("ErrorCopilotNotAuthenticatedRemediation", resourceCulture)!; }
        }

        internal static string ErrorCopilotOverrideTokenRejectedRemediation {
            get { return ResourceManager.GetString("ErrorCopilotOverrideTokenRejectedRemediation", resourceCulture)!; }
        }

        internal static string ErrorCopilotModelNotEntitledRemediation {
            get { return ResourceManager.GetString("ErrorCopilotModelNotEntitledRemediation", resourceCulture)!; }
        }

        internal static string ErrorCopilotStartFailureRemediation {
            get { return ResourceManager.GetString("ErrorCopilotStartFailureRemediation", resourceCulture)!; }
        }

        internal static string ErrorCopilotVerificationTimeoutRemediation {
            get { return ResourceManager.GetString("ErrorCopilotVerificationTimeoutRemediation", resourceCulture)!; }
        }

        internal static string CopilotSetup_VerificationOk {
            get { return ResourceManager.GetString("CopilotSetup_VerificationOk", resourceCulture)!; }
        }

        internal static string BannerCopilotNotAuthenticatedTitle {
            get { return ResourceManager.GetString("BannerCopilotNotAuthenticatedTitle", resourceCulture)!; }
        }

        internal static string BannerCopilotNotAuthenticatedBody {
            get { return ResourceManager.GetString("BannerCopilotNotAuthenticatedBody", resourceCulture)!; }
        }
    }
}
