//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REBUSS.Pure.GitHub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REBUSS.Pure.GitHub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/.
        /// </summary>
        internal static string ApiBaseUrl {
            get {
                return ResourceManager.GetString("ApiBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBUSS.Pure.
        /// </summary>
        internal static string AppDataDirectoryName {
            get {
                return ResourceManager.GetString("AppDataDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found at ref &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorFileNotFoundAtRef {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundAtRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found in Pull Request #{1}.
        /// </summary>
        internal static string ErrorFileNotFoundInPullRequest {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundInPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========================================
        ///AUTHENTICATION REQUIRED
        ///========================================
        ///
        ///REBUSS.Pure requires authentication to access GitHub.
        ///
        ///OPTION 1 — GitHub CLI (recommended, no PAT needed):
        ///
        ///  Install GitHub CLI: https://cli.github.com/
        ///  Then run:
        ///
        ///    gh auth login
        ///
        ///  After that, restart your IDE or run:
        ///
        ///    rebuss-pure init
        ///
        ///OPTION 2 — Personal Access Token (PAT):
        ///
        ///  1. Go to https://github.com/settings/tokens
        ///  2. Click &apos;Generate new token (classic)&apos;
        ///  3. Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorGitHubAuthRequired {
            get {
                return ResourceManager.GetString("ErrorGitHubAuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not contain spaces.
        /// </summary>
        internal static string ErrorPropertyMustNotContainSpaces {
            get {
                return ResourceManager.GetString("ErrorPropertyMustNotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request #{0} not found.
        /// </summary>
        internal static string ErrorPullRequestNotFound {
            get {
                return ResourceManager.GetString("ErrorPullRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auth token.
        /// </summary>
        internal static string GhCliAuthTokenArgs {
            get {
                return ResourceManager.GetString("GhCliAuthTokenArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gh.
        /// </summary>
        internal static string GhCliExecutable {
            get {
                return ResourceManager.GetString("GhCliExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to git.
        /// </summary>
        internal static string GitExecutable {
            get {
                return ResourceManager.GetString("GitExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.github+json.
        /// </summary>
        internal static string GitHubAcceptHeader {
            get {
                return ResourceManager.GetString("GitHubAcceptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022-11-28.
        /// </summary>
        internal static string GitHubApiVersion {
            get {
                return ResourceManager.GetString("GitHubApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-GitHub-Api-Version.
        /// </summary>
        internal static string GitHubApiVersionHeader {
            get {
                return ResourceManager.GetString("GitHubApiVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github-config.json.
        /// </summary>
        internal static string GitHubConfigFileName {
            get {
                return ResourceManager.GetString("GitHubConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-RateLimit-Remaining.
        /// </summary>
        internal static string GitHubRateLimitRemainingHeader {
            get {
                return ResourceManager.GetString("GitHubRateLimitRemainingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to X-RateLimit-Limit.
        /// </summary>
        internal static string GitHubRateLimitLimitHeader {
            get {
                return ResourceManager.GetString("GitHubRateLimitLimitHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry-After.
        /// </summary>
        internal static string GitHubRetryAfterHeader {
            get {
                return ResourceManager.GetString("GitHubRetryAfterHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to application/vnd.github.raw+json.
        /// </summary>
        internal static string GitHubRawContentAcceptHeader {
            get {
                return ResourceManager.GetString("GitHubRawContentAcceptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote get-url origin.
        /// </summary>
        internal static string GitRemoteGetUrlArgs {
            get {
                return ResourceManager.GetString("GitRemoteGetUrlArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBUSS-Pure.
        /// </summary>
        internal static string HttpUserAgentProduct {
            get {
                return ResourceManager.GetString("HttpUserAgentProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binary file.
        /// </summary>
        internal static string SkipReasonBinaryFile {
            get {
                return ResourceManager.GetString("SkipReasonBinaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file deleted.
        /// </summary>
        internal static string SkipReasonFileDeleted {
            get {
                return ResourceManager.GetString("SkipReasonFileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file renamed.
        /// </summary>
        internal static string SkipReasonFileRenamed {
            get {
                return ResourceManager.GetString("SkipReasonFileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full file rewrite.
        /// </summary>
        internal static string SkipReasonFullFileRewrite {
            get {
                return ResourceManager.GetString("SkipReasonFullFileRewrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generated file.
        /// </summary>
        internal static string SkipReasonGeneratedFile {
            get {
                return ResourceManager.GetString("SkipReasonGeneratedFile", resourceCulture);
            }
        }
    }
}
