//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REBUSS.Pure.AzureDevOps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REBUSS.Pure.AzureDevOps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBUSS.Pure.
        /// </summary>
        internal static string AppDataDirectoryName {
            get {
                return ResourceManager.GetString("AppDataDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az.
        /// </summary>
        internal static string AzCliExecutable {
            get {
                return ResourceManager.GetString("AzCliExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account get-access-token --resource {0} --output json.
        /// </summary>
        internal static string AzCliGetTokenArgsTemplate {
            get {
                return ResourceManager.GetString("AzCliGetTokenArgsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.json.
        /// </summary>
        internal static string AzureDevOpsConfigFileName {
            get {
                return ResourceManager.GetString("AzureDevOpsConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        internal static string ContentTypeHtml {
            get {
                return ResourceManager.GetString("ContentTypeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps returned an authentication page instead of API data (HTTP {0}). Your token is likely expired or invalid. Run &apos;rebuss-pure init&apos; or &apos;az login&apos; to re-authenticate..
        /// </summary>
        internal static string ErrorAuthPageInsteadOfApiData {
            get {
                return ResourceManager.GetString("ErrorAuthPageInsteadOfApiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========================================
        ///AUTHENTICATION REQUIRED
        ///========================================
        ///
        ///REBUSS.Pure requires authentication to access Azure DevOps.
        ///
        ///OPTION 1 — Azure CLI (recommended, no PAT needed):
        ///
        ///  Run the following command to log in:
        ///
        ///    az login
        ///
        ///  The server will automatically acquire a token for Azure DevOps.
        ///  You can also run &apos;rebuss-pure init&apos; (without --pat) to log in
        ///  during initialization.
        ///
        ///  If Azure CLI is not installed:
        ///    https://learn.microsoft.com/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorAzureDevOpsAuthRequired {
            get {
                return ResourceManager.GetString("ErrorAzureDevOpsAuthRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps configuration is incomplete.
        /// </summary>
        internal static string ErrorConfigurationIncomplete {
            get {
                return ResourceManager.GetString("ErrorConfigurationIncomplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found at ref &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorFileNotFoundAtRef {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundAtRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found in Pull Request #{1}.
        /// </summary>
        internal static string ErrorFileNotFoundInPullRequest {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundInPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not contain spaces.
        /// </summary>
        internal static string ErrorPropertyMustNotContainSpaces {
            get {
                return ResourceManager.GetString("ErrorPropertyMustNotContainSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request #{0} not found.
        /// </summary>
        internal static string ErrorPullRequestNotFound {
            get {
                return ResourceManager.GetString("ErrorPullRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to git.
        /// </summary>
        internal static string GitExecutable {
            get {
                return ResourceManager.GetString("GitExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote get-url origin.
        /// </summary>
        internal static string GitRemoteGetUrlArgs {
            get {
                return ResourceManager.GetString("GitRemoteGetUrlArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps.
        /// </summary>
        internal static string ProviderDisplayName {
            get {
                return ResourceManager.GetString("ProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binary file.
        /// </summary>
        internal static string SkipReasonBinaryFile {
            get {
                return ResourceManager.GetString("SkipReasonBinaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file deleted.
        /// </summary>
        internal static string SkipReasonFileDeleted {
            get {
                return ResourceManager.GetString("SkipReasonFileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file renamed.
        /// </summary>
        internal static string SkipReasonFileRenamed {
            get {
                return ResourceManager.GetString("SkipReasonFileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full file rewrite.
        /// </summary>
        internal static string SkipReasonFullFileRewrite {
            get {
                return ResourceManager.GetString("SkipReasonFullFileRewrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generated file.
        /// </summary>
        internal static string SkipReasonGeneratedFile {
            get {
                return ResourceManager.GetString("SkipReasonGeneratedFile", resourceCulture);
            }
        }
    }
}
