//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REBUSS.Pure.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REBUSS.Pure.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer &apos;{Name}&apos; produced section &apos;{Key}&apos;.
        /// </summary>
        internal static string LogReviewContextOrchestratorAnalyzerProducedSection {
            get {
                return ResourceManager.GetString("LogReviewContextOrchestratorAnalyzerProducedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping analyzer &apos;{Name}&apos;: not applicable.
        /// </summary>
        internal static string LogReviewContextOrchestratorSkippingAnalyzer {
            get {
                return ResourceManager.GetString("LogReviewContextOrchestratorSkippingAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff for &apos;{FilePath}&apos;: {HunkCount} hunk(s), old={OldLineCount} lines, new={NewLineCount} lines, {ElapsedMs}ms.
        /// </summary>
        internal static string LogStructuredDiffBuilderDiffCompleted {
            get {
                return ResourceManager.GetString("LogStructuredDiffBuilderDiffCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspicious diff for &apos;{FilePath}&apos;: {HunkCount} hunks (possible generated/binary file).
        /// </summary>
        internal static string LogStructuredDiffBuilderSuspiciousDiff {
            get {
                return ResourceManager.GetString("LogStructuredDiffBuilderSuspiciousDiff", resourceCulture);
            }
        }
    }
}
